#!/usr/bin/env bash
# Export a completed OMGB run as a single, portable markdown handoff file
# consumable by Claude Code, Codex, Cursor, and other markdown-first agents.
#
# Usage:
#   scripts/workflow/export-omgb-handoff.sh <task-slug>
#
# Output (inside the run directory):
#   .grok/omgb/runs/<slug>/omgb-handoff-<slug>.md
#   .grok/omgb/runs/<slug>/omgb-handoff.md          (stable short name when sharing the whole dir)
#
# A copy is also placed at the repo root as omgb-handoff-<slug>.md for convenience.
#
# The generated file is deliberately short, uses real variable expansion,
# and strongly directs the receiving agent to the five canonical artifacts
# (mission.md, state.json, tasks.json, evidence.md, review.md) that contain
# the complete process record.

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <task-slug>"
  echo "Example: $0 omgb-self-audit-agents-md-install-guide"
  exit 1
fi

SLUG="$1"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUNS_ROOT="${OMGB_RUNS_ROOT:-$HOME/.grok/omgb/runs}"
RUN_DIR="$RUNS_ROOT/$SLUG"

if [[ ! -d "$RUN_DIR" ]]; then
  echo "ERROR: run directory not found: $RUN_DIR"
  echo "Available runs:"
  ls -1 "$RUNS_ROOT/" 2>/dev/null || echo "  (none yet)"
  exit 1
fi

MISSION="$RUN_DIR/mission.md"
STATE="$RUN_DIR/state.json"
TASKS="$RUN_DIR/tasks.json"
EVIDENCE="$RUN_DIR/evidence.md"
REVIEW="$RUN_DIR/review.md"

# Short, readable filenames
HANDOFF_LONG="omgb-handoff-$SLUG.md"
HANDOFF_SHORT="omgb-handoff.md"
OUT="$RUN_DIR/$HANDOFF_LONG"
OUT_SHORT="$RUN_DIR/$HANDOFF_SHORT"

if [[ ! -f "$MISSION" || ! -f "$STATE" || ! -f "$EVIDENCE" ]]; then
  echo "ERROR: run is missing required artifacts (mission/state/evidence). Cannot export."
  exit 1
fi

# Extract useful metadata via Node (repo policy: JSON reading belongs in Node, not jq)
read -r PHASE QA REVIEWS ACTIVE < <(node -e "
  let s = {};
  try { s = JSON.parse(require('fs').readFileSync(process.argv[1], 'utf8')); } catch {}
  const out = [
    s.phase       ?? 'unknown',
    s.qaCycles    ?? 0,
    s.reviewRounds ?? 0,
    s.active      ?? false,
  ];
  process.stdout.write(out.join(' ') + '\n');
" "$STATE")
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Build the handoff using unquoted heredocs for proper expansion
cat > "$OUT" <<EOF
# OMGB Handoff — Portable Run Record

**For Claude Code, Codex, Cursor, and other markdown-first agents**

This file was produced by the \`oh-my-grokbuild\` (OMGB) plugin inside Grok Build.
It is a concise summary. The *complete* authoritative record of the run lives in
the five files listed below in the same directory.

You are now acting as the **leader / verifier / next agent** for any remaining work.

---

## Run Artifacts — The Source of Truth

Keep this directory (or at least these five files + this handoff) together when sharing
with another agent. They represent the full OMGB lifecycle and are far more valuable
than this summary alone.

| File            | Purpose |
|-----------------|---------|
| \`mission.md\`    | Original goal, scope, non-goals, constraints, and acceptance criteria for the entire run |
| \`state.json\`    | Current phase, timestamps, QA cycles, review rounds, active roles, blockers |
| \`tasks.json\`    | Every task with id, title, ownerRole, status, acceptance criteria, dependencies, and verification commands |
| \`evidence.md\`   | Full chronological log: research, commands executed, outputs, decisions, rationale, and intermediate results |
| \`review.md\`     | All code, UX, security, performance, and verifier reviews with explicit verdicts (APPROVE / COMMENT / REQUEST CHANGES) |

**Recommended usage in Claude Code / Codex / Cursor:**
- Drag the whole run directory into your workspace, or
- Reference the files explicitly: \`@mission.md @evidence.md @tasks.json\`
- Start your prompt with: "Continue this OMGB run. Read the five artifacts above plus this handoff first."

---

## Mission

EOF

# Append the real mission (it already has its own # header)
cat "$MISSION" >> "$OUT"

cat >> "$OUT" <<EOF

---

## Final State

- **Phase:** \`$PHASE\`
- **QA cycles completed:** $QA
- **Review rounds completed:** $REVIEWS
- **Still active:** $ACTIVE

---

## How to Continue (receiving agent instructions)

1. Read the five artifacts listed in the table above (especially \`evidence.md\` for decisions and \`tasks.json\` for open work).
2. Treat the last non-completed tasks in \`tasks.json\` as your backlog.
3. Follow a disciplined process (intake → grounding → plan → execute → verify → review).
4. When you finish work, run the verification commands recorded in the evidence and produce your own handoff or summary.

The original Grok OMGB run used strict phase gates and a single accountable leader.
You now own the next segment of that same contract.

---

**Original run (Grok workspace):** \`.grok/omgb/runs/$SLUG/\`

**Handoff generated by:** \`scripts/workflow/export-omgb-handoff.sh\`
**Generated at:** $NOW

For hybrid team workflows, recommended prompts, and how to set up your CLAUDE.md / AGENTS.md to automatically pick up OMGB handoffs, see the guide that travels with the plugin:

\`docs/WORKING-WITH-OTHER-AGENTS.md\`

This handoff + the five sibling files give you the same working memory the original leader had.
EOF

# Also create the stable short name inside the run dir (excellent when sharing the folder)
cp "$OUT" "$OUT_SHORT"

# Convenience copy at repo root (short name)
cp "$OUT" "$ROOT/$HANDOFF_LONG"

echo "Handoff exported:"
echo "  $OUT"
echo "  $OUT_SHORT   (stable name when sharing the whole run dir)"
echo "  $ROOT/$HANDOFF_LONG   (repo-root convenience copy)"
echo
echo "Recommended sharing command for Claude users:"
echo "  tar -czf omgb-run-$SLUG.tar.gz -C $RUN_DIR ."
echo "  # or simply zip the five files + $HANDOFF_LONG"
